### ISSUE TITLE
different font

### ISSUE THREAD

**Issue by elshnkhll** [upiir/character_display_big_digits#1]
Please accept my humble contribution to your very challenging project.
BTW: I have used only 7 of 8 custom chars.

**Comment by elshnkhll** [comment]
![digits](https://user-images.githubusercontent.com/31281/232606610-2a9608f2-1ba5-49c0-8dde-4f4afc170822.png)

**Comment by elshnkhll** [comment]
![digits](https://user-images.githubusercontent.com/31281/232607202-b3c64779-8d3a-49a1-9049-274476ca092b.png)

**Comment by upiir** [comment]
Looks great! I was trying to always connect all the pieces together, but I really like your approach since it´s still readable. Great work, and thank you for your contribution.
